### ISSUE TITLE
Help Required for developing expression evaluation parser!

### ISSUE THREAD

**Issue by aamironline** [mna/pigeon#102]
Hello,

Hope you are doing great! Thank you very much for developing such a wonderful library.

For one of our project (https://github.com/maniartech/x/), we are developing expression evaluator in Golang. We have used [expr](https://github.com/antonmedv/expr) library for now. But would like to replace with our own evaluator/parser. We do not want to write from the scratch. The pigeon seems to provide perfect solution for our requirements. This seems to be easy. I started with changing calculator parser provided with the pigeon library. However, it is not working out.

I am new to PEG ecosystem, can anyone help me develop this parser! I am open to start a new MIT licensed open source project for this expression evaluator.

Thanks and Regards.

The expression evaluator has got following syntax!

```
-a-----a-----b-----b----------c----d------------l-------c----e---
SUM(AVERAGE(varA, obj.key, 10 + (2 + 3), [1, 23, 4]), 10 - 2, x)
-------------e-----e----------e--------------e-----------e----e---

-a---o-k---v----k---v----k------v--------
KEYS({ a: true, b: false, c: [1, 2, 3] })
------------t---------t-------l------------
```
```yaml
- a: Function Name
- b: Variables, it should be JSON like variable with dot notation support
- c: Expression, Could be mathematical (+ - * /), comparison(== != > etc..), boolean (| & ~) etc...
- d: Bracketed Expression
- e: Comma separated function parameters
- o: JSON like object with nested object and array support
- k: The object key
- v: The object value
- l: The list (array) value in object 
- t: The boolean value
```
